spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5434/server-db
    username: postgres
    password: dangercodex
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
