services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dangercodex
      POSTGRES_DB: server-db
    ports:
      - "5434:5432"